trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- group: "SECURE_TOKENS"
- name: snyk_token
  value: $[variables.SNYKTOKEN]


steps:
- script: |
    curl -L https://github.com/snyk/snyk/releases/download/v1.1200.0/snyk-linux -o snyk
    chmod +x snyk
    sudo mv snyk /usr/local/bin/snyk
  displayName: "Install snyk"
  
- script: |
    mvn clean package
  displayName: "Building Azure DevOps App"

- script: |
    mvn clean test
  displayName: "Testing Azure DevOps App"

#- script: |
#    mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=azuredevopsdevsecopsorg -Dsonar.projectKey=azuredevopsdevsecopsprojectkey -Dsonar.login=$(sonar_token)
#  displayName: "Integrate SAST using SonarCloud to populate code coverage and secure pipeline variable in Azure DevOps DevSecOps Pipeline"

- script: |
    #SNYK_TOKEN='6e89be83-fcc3-4bf8-9954-622c6f759b87'
    SNYK_TOKEN=${snyk_token}
    /usr/local/bin/snyk auth $SNYK_TOKEN
    /usr/local/bin/snyk test
    exit 0
  displayName: "SCA Scan Azure DevOps App"
  
- script: |
      wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz
      tar -xvf ZAP_2.11.1_Linux.tar.gz
      cd ZAP_2.11.1
      ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout /home/vsts/work/1/a/zap_report.html 
  displayName: "DAST Scan Azure DevOps App"

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: zap_report.html