trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: "SECURE_TOKENS"
- name: snyk_token
  value: $[variables.SNYKTOKEN]

steps:
- script: |
    SNYK_TOKEN=$(snyk_token)
    export SNYK_TOKEN
    snyk $SNYK_TOKEN
    mvn -X snyk:test -fn 
  displayName: "Integrate SCA scan using Snyk in ADO DevSecOps Pipeline"