trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- group: "SECURE_TOKENS"
- name: snyk_token
  value: $[variables.SNYKTOKEN]


steps:
- task: Bash@3
  displayName: Download and install trivy
  inputs:
    targetType: 'inline'
    script: |
      trivyVersion='0.44.1'
      sudo apt-get install rpm
      wget https://github.com/aquasecurity/trivy/releases/download/v${trivyVersion}/trivy_${trivyVersion}_Linux-64bit.deb
      sudo dpkg -i trivy_${trivyVersion}_Linux-64bit.deb
      trivy -v 

- task: Bash@3
  displayName: Scan image
  inputs:
    targetType: 'inline'
    script: |
      #trivy image  nginx:latest
      #trivy image  --exit-code 0 --severity HIGH,CRITICAL --format template --template "@./JUnit.tpl" -o junit-report-high-crit.xml nginx:latest
      trivy image  --severity LOW,MEDIUM --format template --template "@./JUnit.tpl" -o junit-report-low-med.xml nginx:latest
    workingDirectory: '$(System.DefaultWorkingDirectory)'

#- task: PublishTestResults@2
#  inputs:
#    testResultsFormat: 'JUnit'
#    testResultsFiles: '**/junit-report-high-crit.xml'
#    mergeTestResults: true
#    failTaskOnFailedTests: true
#    testRunTitle: 'Trivy'

#- task: PublishTestResults@2
#  inputs:
#    testResultsFormat: 'JUnit'
#    testResultsFiles: '**/junit-report-low-med.xml'
#    mergeTestResults: true
#    failTaskOnFailedTests: true
#    testRunTitle: 'Trivy'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.DefaultWorkingDirectory)'
    artifactName: junit-report-low-med.xml
