trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: "SECURE_TOKENS"
- name: snyk_token
  value: $[variables.SNYKTOKEN]


steps:
- script: |
    curl -L https://github.com/snyk/snyk/releases/download/v1.1200.0/snyk-linux -o snyk
    chmod +x snyk
    sudo mv snyk /usr/local/bin/snyk
  displayName: "Install snyk"
  
- script: |
    mvn clean package
  displayName: "Building Azure DevOps App"

- script: |
    mvn clean test
  displayName: "Testing Azure DevOps App"

- script: |
    SNYK_TOKEN='6e89be83-fcc3-4bf8-9954-622c6f759b87'
    snyk auth $SNYK_TOKEN
    snyk test
  displayName: "SCA Scan Azure DevOps App"