trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: "SECURE_TOKENS"
- name: snyk_token
  value: $[variables.SNYKTOKEN]


steps:
- script: |
    mvn clean package
  displayName: "Building Azure DevOps App"

- script: |
    mvn clean test
  displayName: "Testing Azure DevOps App"

- script: |
    SNYK_TOKEN='6e89be83-fcc3-4bf8-9954-622c6f759b87'
    #SNYK_TOKEN=$(snyk_token)
    export SNYK_TOKEN
    snyk auth $SNYK_TOKEN
    snyk test
  displayName: "SCA Scan Azure DevOps App"