trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: "SECURE_TOKENS"
- name: snyk_token
  value: $[variables.SNYKTOKEN]

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -L https://github.com/snyk/snyk/releases/download/v<VERSION>/snyk-linux -o snyk
      chmod +x snyk
      sudo mv snyk /usr/local/bin/snyk
- script: |
    SNYK_TOKEN=$(snyk_token)
    export SNYK_TOKEN
    snyk $SNYK_TOKEN
    #mvn -X snyk:test -fn 
    snyk test
  displayName: "Integrate SCA scan using Snyk in ADO DevSecOps Pipeline"